---
spring:
  profiles: dev

eureka:
  host: localhost
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.username:szss}:${eureka.password:Songshu619}@localhost:8761/eureka/

---
spring:
  profiles: discovery01

eureka:
  instance:
    hostname: discovery01
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eureka.username:szss}:${eureka.password:Songshu619}@${eureka.host:discovery02}:${eureka.port:8761}/eureka/

---
spring:
  profiles: discovery02

eureka:
  instance:
    hostname: discovery02
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${eureka.username:szss}:${eureka.password:Songshu619}@${eureka.host:discovery01}:${eureka.port:8761}/eureka/
